### ISSUE TITLE
Whitespace interpretation

### ISSUE THREAD

**Issue by philanc** [jevko/specifications#1] opened 2022-10-25 22:00 UTC
I am not sure I understand the "whitespace rule":  

> There are no special rules for whitespace. All whitespace characters are captured by the Character rule.

Considering the `dog` example. In the following fragment:
```
Conservation status [Domesticated]
Scientific classification [
  Kingdom [Animalia]
  ...
```
The "Scientific classification" key, according to the rule is actually the string `"\nScientific classification "` (with a trailing space)  and the key "Kingdom" is actually `"\n  Kingdom "`, right?

And on Windows where  the end of line is `"\r\n"`, this document would have different key values...

Is it what you intended?  

Shouldn't the specification clarify how leading and trailing whitespaces (including newlines) are to be interpreted?

Phil

**Comment by djedr** [comment] 2022-10-25 22:27
Hello,

Thanks for the question!

Indeed there are no rules for whitespace -- this is by design.

You point out a good reason why this might be the right choice: operating system differences.

Whitespace is the concern of one level above Jevko, which should ideally be occupied by standardized formats.

One such format, which does not have a spec yet, but is pretty much defined is codenamed Easy Jevko. Here are libraries for working with it in JS and Lua that I wrote (~ v0.1.0):

* https://github.com/jevko/easyjevko.js
* https://github.com/jevko/easyjevko.lua

This format specifies how to interpret the different parts of Jevko into programming language data structures, such as tables/maps/objects, arrays/lists, and strings. This includes the treatment of whitespace in a sensible way: in your example `Scientific classification` and `Kingdom` would be keys in a map and they would be properly trimmed. Notice that this format does that automatically and disallows untrimmed keys entirely (which is a good thing in 99.9% of cases).

This should certainly be clarified somewhere. I'm not sure specification is the right place, but I'll figure something out.

Thanks again for your input!

**Comment by philanc** [comment] 2022-10-25 22:56
Thanks for your prompt response. I will have a look at Easy Jevko!

**Comment by djedr** [comment] 2023-09-08 21:46
Huh, I forgot about this issue. Found it today and it inspired me to write this: https://github.com/jevko/writing/blob/main/2023-09-08-jevko-whitespace.md

With that I'm closing the issue.

**Closed as completed by djedr** 2023-09-08 21:46 UTC
Labels: documentation
